# Postgre baasist andmete pärimine

In [2]:
!pip3 install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 3.8 MB/s eta 0:00:01
   ------------------ --------------------- 1.3/2.8 MB 4.0 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.8 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.4 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import psycopg2

In [7]:
conn = psycopg2.connect(
    host="localhost",
    database="cafe",
    user="postgres",
    password="160992"
)
df = pd.read_sql("Select * FROM cafe.cafe_budget", conn)
conn.close()
df

C:\Users\jaana\AppData\Local\Temp\ipykernel_25816\2558221624.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("Select * FROM cafe.cafe_budget", conn)

   year_month  budget_sum
0     2023-01        6500
1     2023-02        6000
2     2023-03        6500
3     2023-04        6500
4     2023-05        6500
5     2023-06        7000
6     2023-07        7000
7     2023-08        7000
8     2023-09        7000
9     2023-10        6500
10    2023-11        6500
11    2023-12        7000

In [12]:
!pip3 install requests

Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   -------- ------------------------------- 1/5 [idna]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.7 idna-3.11 requests-2.33.1 urllib3-2.6.3

  WARNING: The script normalizer.exe is installed in 'C:\Users\jaana\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import requests
import pandas as pd

In [14]:
response=requests.get("https://jsonplaceholder.typicode.com/posts")
response

In [15]:
df = pd.DataFrame(response.json())
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

## Vigade haldus

In [17]:
countries = ["Estonia", "Latvia", "Lithuania"]

try:
    fourth_country = countries [4]
except IndexError:
    print("No fourth country..")

No fourth country..

In [ ]:
def numeric_year(year_str: str) -> int:
    year_number_components = year_str.split (" ")
    year_number_str = year_number_components[0]
    year_era_notation_str = year_number_components[1] 
    
    if year_era_notation_str == "A.D.":
        return int(year_number_str)
    elif year_era_notation_str == "B.C.":
        return -int(year_number_str)
    else:
       raise ValueError(f" '{}")

print(numeric_year("2024 A.D.")) # 2024
print(numeric_year("1 B.C.")) # -1

2024
-1